### ISSUE TITLE
Plugin does not block Twitter Cookie

### ISSUE THREAD

**Issue by 00travelgirl00** [epiphyt/embed-privacy#2] opened 2018-12-06 15:34 UTC
I wanted to use the plugin to block a twitter cookie. Unfortunately the cookie is still set for the Twitter Embed. 
It does blocked videopress. 

Example Post: https://www.wp1x1.de/warum-contributen-zu-wordpress/

<img width="1439" alt="bildschirmfoto 2018-12-06 um 16 31 54" src="https://user-images.githubusercontent.com/21318377/49593761-9bc98d00-f974-11e8-8c06-1d826d35d824.png">

**Comment by KittMedia** [comment] 2018-12-07 17:32
Would you please try to create a new post with another Twitter status link and view the preview of this post? Does the problem also occur in this preview?

If yes, it seems that there is another problem (maybe with the Enfold Theme or another plugin), otherwise it seems to be a caching issue, because every embed code is cached by WordPress.

**Comment by krafit** [comment] 2018-12-09 16:06
Well, I ran into the same issue with a cookie on https://krautpress.de/2018/state-of-the-word-2018/ with Chrome Version 70.0.3538.110.

**Comment by KittMedia** [comment] 2018-12-09 16:48
As already mentioned directly, the behavior on your site is different, @krafit, and is in relation with WP Rocket, which is not installed on the website of @00travelgirl00.

Maybe the Simple Cache plugin is the problem in this case.

**Comment by goaround** [comment] 2020-11-29 22:29
I think the problem is that the then Plugin checks serversite if the consent cookie is set: https://github.com/epiphyt/embed-privacy/blob/e5d7d792ca81d830b638fab37e5bb98f9b8e8710/inc/class-embed-privacy.php#L248

If the cookie is set and then the request get‘s cached by a caching plugin, the Embed is not blocked for the next request served from the cache.

I would suggest to set & check the cookie only on the frontend with Javascript. If the cookie is set, remove the consent overlay and load the embed.

**Comment by KittMedia** [comment] 2020-11-30 06:41
As far as I know, at least on KrautPress from @krafit there is no such caching plugin enabled.

And I don’t like the idea to handle everything on client side since it results in a bigger and more complex JavaScript overall. Maybe we can add this as fallback, if a user explicitly enables it, though.

**Comment by goaround** [comment] 2020-11-30 10:05
I think the additional Javascript code would be very small. There is already a `get_cookie` function. You just have to check in one of the two for-Loops if the cookie is set and then hide the overlay.

If you extract this https://github.com/epiphyt/embed-privacy/blob/master/assets/js/embed-privacy.js#L13 anonyms function to a named function, you just have to run this function if the corresponding cookie is set.

**Comment by krafit** [comment] 2020-12-17 08:47
> And I don’t like the idea to handle everything on client side
I think I'm with @MatzeKitt on this one. A "very small" amount of JS sounds good, as far as I know feature creep, small pieces of code add up over time.

But I'd like to give it a try and see if @goaround's proposal works. As Matze already mentioned, there might be a path to add this as an optional feature.

**Comment by MatzeKitt** [comment] 2020-12-17 09:01
I created a new issue (#7) for this since it doesn’t belong to the initial issue of @00travelgirl00.

**Comment by MatzeKitt** [comment] 2021-01-18 10:30
@00travelgirl00 Which theme and editor are you using? After I took another look it doesn’t seem to be a default editor (neither Classic Editor nor Gutenberg) and the embed seems to get processed otherwise. I think, this prevents Embed Privacy currently from detect the embed.

**Comment by Zodiac1978** [comment] 2021-03-29 11:02
> Which theme and editor are you using?

>  I'm using the classic Editor (with Enfold Theme, but not with the Layout Builder)

**Comment by MatzeKitt** [comment] 2021-03-29 11:49
Oh yeah. 🙈

However, we’re already discussing this issue via Slack and it seems to be a problem with Enfold. Unfortunately, I don’t have Enfold and thus cannot test it.

**Comment by Zodiac1978** [comment] 2022-10-23 14:21
I tried to reproduce this with Enfold and Classic Editor activated, but the blocking of the embed is working without any problems for me.

Is there a caching plugin involved @00travelgirl00 ?

What are your Embed Privacy settings? JS option enabled? Can you share your active plugins?

Have you tried the troubleshooting mode of the Health Check plugin? Maybe some other plugin is interfering here ...

**Comment by MatzeKitt** [comment] 2023-03-11 20:09
Will close the issue for now. If it still persists and you have time to answer the open questions, @00travelgirl00, feel free to reopen it. 🙂

**Closed by MatzeKitt** 2023-03-11 20:09 UTC
Labels: help wanted, awaiting feedback
